"""init

Revision ID: 04447c6d7b12
Revises: 
Create Date: 2023-12-14 19:02:24.606198

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = "04447c6d7b12"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dormitories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("img", sa.String(), nullable=False),
        sa.Column("scheme", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dormitories_address"), "dormitories", ["address"], unique=False
    )
    op.create_index(
        op.f("ix_dormitories_description"), "dormitories", ["description"], unique=False
    )
    op.create_index(op.f("ix_dormitories_img"), "dormitories", ["img"], unique=False)
    op.create_index(op.f("ix_dormitories_name"), "dormitories", ["name"], unique=False)
    op.create_index(
        op.f("ix_dormitories_scheme"), "dormitories", ["scheme"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "dormitory_photos",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("dormitory_id", sa.Integer(), nullable=False),
        sa.Column("img", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dormitory_id"], ["dormitories.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dormitory_photos_img"), "dormitory_photos", ["img"], unique=False
    )
    op.create_table(
        "floors",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("dormitory_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dormitory_id"], ["dormitories.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_floors_name"), "floors", ["name"], unique=False)
    op.create_table(
        "user_profiles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "user_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False
        ),
        sa.Column("card_number", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("birth_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("grant_order_number", sa.String(), nullable=True),
        sa.Column("transfer_order_number", sa.String(), nullable=True),
        sa.Column("transfer_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("birth_place", sa.String(), nullable=True),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("concession", sa.Boolean(), nullable=False),
        sa.Column("gender", sa.String(), nullable=True),
        sa.Column("course", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_profiles_card_number"),
        "user_profiles",
        ["card_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_profiles_name"), "user_profiles", ["name"], unique=False
    )
    op.create_table(
        "rooms",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("floor_id", sa.Integer(), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["floor_id"], ["floors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "person_attached_rooms",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "user_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False
        ),
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["room_id"], ["rooms.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("person_attached_rooms")
    op.drop_table("rooms")
    op.drop_index(op.f("ix_user_profiles_name"), table_name="user_profiles")
    op.drop_index(op.f("ix_user_profiles_card_number"), table_name="user_profiles")
    op.drop_table("user_profiles")
    op.drop_index(op.f("ix_floors_name"), table_name="floors")
    op.drop_table("floors")
    op.drop_index(op.f("ix_dormitory_photos_img"), table_name="dormitory_photos")
    op.drop_table("dormitory_photos")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_dormitories_scheme"), table_name="dormitories")
    op.drop_index(op.f("ix_dormitories_name"), table_name="dormitories")
    op.drop_index(op.f("ix_dormitories_img"), table_name="dormitories")
    op.drop_index(op.f("ix_dormitories_description"), table_name="dormitories")
    op.drop_index(op.f("ix_dormitories_address"), table_name="dormitories")
    op.drop_table("dormitories")
    # ### end Alembic commands ###
